# Generated by Django 4.1.2 on 2023-01-17 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_book_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mng_code', models.PositiveIntegerField()),
                ('mng_name', models.CharField(max_length=50)),
                ('mng_grade', models.IntegerField()),
                ('mng_location', models.CharField(max_length=50)),
                ('mng_project', models.CharField(max_length=50)),
                ('mng_role', models.CharField(max_length=50)),
                ('mng_status', models.CharField(max_length=50)),
                ('mng_DOJ', models.DateField()),
                ('mng_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.PositiveIntegerField()),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_grade', models.IntegerField()),
                ('emp_location', models.CharField(max_length=50)),
                ('emp_project', models.CharField(max_length=50)),
                ('emp_role', models.CharField(max_length=50)),
                ('emp_status', models.CharField(max_length=50)),
                ('emp_DOJ', models.DateField()),
                ('emp_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
